package corejava.exception.demo;

public class ExceptionDemo {

	public static void main(String[] args) {
	
		try{
			
			int x=2/0;
			
		}
		catch(ArithmeticException e){
			e.printStackTrace();
		}
		catch(Throwable[] e){
			e.printStackTrace();
		}
		finally{
			System.out.println("In finally");
		}
	}

}
